//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps


Before using this Quick start, customers first need to:

•	Have an administrator account created on the VMware Orchestrator
•	Have a Hub Profile already created and to be assigned to the Hub Cluster 
•	Have segments already defined on the VMware Orchestrator
•	Have a policy file already defined for the AWS Cloud WAN. See example here (insert hyperlink here https://docs.aws.amazon.com/vpc/latest/cloudwan/cloudwan-policy-examples.html)
•	Have A AWS S3 bucket to host the *.json files (which must be in the same region as the Core Network Edge to be deployed)
•	Ensure there’s no quota limitation (VPC, Site-to-Site VPN)

Note: In this document, we assume that for every VPC attachment there’s only one subnet part of that VPC.
Note2: In this document, we assume there’s no other “NSD via Edge” configuration. Else this may cause the Site-to-Site VPN to fail. 
